import type { FunctionalComponent } from "preact"

const Bookmarklet: FunctionalComponent = () => {
  return (
    <a href='javascript:(function(){function _getSelection(e){if(void 0===window.getSelection)return{hasSelection:!1,html:"",textFragment:""};const n=window.getSelection();if(!n||n.rangeCount<1)return{hasSelection:!1,html:"",textFragment:""};const{status:t,fragment:o}=e(n),i=_makeTextFragmentDirective(t,o),r=window.document.createElement("div");for(let e=0,t=n.rangeCount;e<t;++e)r.appendChild(n.getRangeAt(e).cloneContents());const a=r.innerHTML;return{hasSelection:Boolean(a),html:a,textFragment:i}}function _makeTextFragmentDirective(e,n){if(0!==e)return"";const t=n.prefix?`${encodeURIComponent(n.prefix)}-,`:"",o=n.suffix?`,-${encodeURIComponent(n.suffix)}`:"";return`#:~:text=${t}${encodeURIComponent(n.textStart)}${n.textEnd?`,${encodeURIComponent(n.textEnd)}`:""}${o}`}function _makeObsidianNoteContent({author:e,body:n,excerpt:t,selection:o,title:i,url:r}){let a=new URL(r);a.search="",a.hash="",a=a.toString();const l=new Date;if(o.hasSelection){return`> [!quote] ${l.toLocaleDateString(void 0,{weekday:"short",year:"numeric",month:"short",day:"numeric",hour:"numeric",minute:"numeric"})} &amp;bull; [Source](${a}${o.textFragment})\n\n${n}\n\n---\n\n`}{const o=t!==i?t:"",[r]=l.toISOString().split("T"),c=`[${i}](${a})`;return`---\naliases:\nclipping_author: ${e||""}\nclipping_url: ${a}\ncreated_at_unix: ${Math.round(Date.now()/1e3)} \nsummary: ${o}\n---\n\n%%\ndates:: [[${r}]]\nrelated::\n%%\n\n#clipping\n\n> [!info]\n> ${c}${e?" by "+e:""}\n\n${n}\n`}}function _makeObsidianUri({config:e,content:n,selection:t,title:o}){const i={content:n,file:`${t.hasSelection?e.selectionFolderName:e.folderName}/${o.replace(/:/g,"").replace(/\//g,"-").replace(/\\/g,"-")}`};t.hasSelection&amp;&amp;(i.append="true");return`obsidian://new?${Object.entries(i).map((([e,n])=>`${e}=${encodeURIComponent(n)}`)).join("&amp;")}`}Promise.all([import("https://cdn.jsdelivr.net/npm/@mozilla/readability/+esm"),import("https://cdn.jsdelivr.net/npm/turndown/+esm"),import("https://cdn.jsdelivr.net/npm/text-fragments-polyfill/dist/fragment-generation-utils.js/+esm"),Promise.resolve({folderName:"Clippings",selectionFolderName:"Clippings/Quotes"})]).then((([e,n,t,o])=>{const{Readability:i}=e.default,{default:r}=n,{generateFragment:a}=t,l=_getSelection(a),{byline:c,content:s,excerpt:d,title:m}=new i(window.document.cloneNode(!0)).parse(),u=_makeObsidianUri({config:o,content:_makeObsidianNoteContent({author:c,body:new r({headingStyle:"atx",hr:"---",bulletListMarker:"-",codeBlockStyle:"fenced"}).turndown(l.html||s),excerpt:d,selection:l,title:m,url:window.document.URL}),selection:l,title:m});window.document.location.href=u})).catch((e=>{alert("Failed to clip to Obsidian\n\n"+e+"\n\n(see the browser developer console for more details)")}));}());'>
      Clip to Obsidian
    </a>
  )
}

export default Bookmarklet
